name: second Work Flow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone frontend from git
        run: git clone https://github.com/AnandMaharana2004/storage-app-frontend.git
      
      - name: Install dependencies
        run: cd storage-app-frontend && npm install
      
      - name: Create .env file
        run: echo "ALLOW_HOST_NAME=devzoon.xyz" > storage-app-frontend/.env
      
      - name: Build project
        run: cd storage-app-frontend && npm run build
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Upload to S3
        run: cd storage-app-frontend && aws s3 sync dist/ "s3://${{ secrets.S3_BUCKET_NAME }}/" --delete